import{a as b,S as L,i}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const w="https://pixabay.com/api/",S="49590531-00b723f692e526587c18c8f84";async function q(o,t){try{return(await b.get(w,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(a){throw console.error("Failed to fetch data from Pixabay API:",a),a}}const u=document.querySelector(".gallery"),f=document.querySelector(".load-more"),m=document.querySelector(".loader");let v=new L(".gallery a",{captionsData:"alt",captionDelay:250});function P(){u.innerHTML=""}function $(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:p,downloads:g})=>`
        <li class="gallery-item">
          <a href="${s}">
            <img class="item-img" src="${a}" alt="${e}" />
          </a>
          <div class="info">
            <p><b>Likes</b> ${r}</p>
            <p><b>Views</b> ${n}</p>
            <p><b>Comments</b> ${p}</p>
            <p><b>Downloads</b> ${g}</p>
          </div>
        </li>`).join("");u.insertAdjacentHTML("beforeend",t),v.refresh()}function M(){m.classList.remove("hidden")}function B(){m.classList.add("hidden")}function O(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}const x=document.querySelector(".form"),A=document.querySelector(".gallery"),E=document.querySelector(".load-more");document.querySelector(".loader");l();let c=1,h="";const H=15;let d=0;x.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements.search.value.trim();if(!t){i.error({message:"Enter your search word!"});return}h=t,c=1,P(),l(),await y()});E.addEventListener("click",async()=>{c+=1,await y(!0)});async function y(o=!1){M();try{const t=await q(h,c);if(d=t.totalHits,t.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}$(t.hits),o&&D();const a=Math.ceil(d/H);c>=a?(l(),i.info({message:"We are sorry, but you have reached the end of search results."})):O()}catch{i.error({message:"An error occurred when getting the pictures"})}finally{B()}}function D(){const o=A.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
